add unit test suite & case for author model
- failing due to enum not being handled by sqlite properly:
IntegrityError: (sqlite3.IntegrityError) CHECK constraint failed: author [SQL: u'INSERT INTO author (first_name, last_name, gender) VALUES (?, ?, ?)'] [parameters: ('first1', 'last1', 'U')]